createOrReplace
    table Tabla_Medidas

        measure 'Suma Stock Libre' = 
            SUM(VW_Tipo_stock_materiales[StockLibreUtilizacion])

        measure 'Suma Stock Transferencia' = 
            SUM(VW_Tipo_stock_materiales[StockTransferencia])

        measure 'Suma Stock Inspecci贸n' = 
            SUM(VW_Tipo_stock_materiales[StockInspeccion])

        measure 'Suma Stock no Libre' = 
            SUM(VW_Tipo_stock_materiales[Stocknolibre])

        measure 'Suma Stock Bloqueado' = 
            SUM(VW_Tipo_stock_materiales[Bloqueado])

        measure 'Suma Cantidad Total' = 
            SUM(VW_Tipo_stock_materiales[cant_total])

        measure '% Stock Libre' = 
            DIVIDE([Suma Stock Libre], [Suma Cantidad Total])

        measure '% Stock Transferencia' = 
            DIVIDE([Suma Stock Transferencia], [Suma Cantidad Total])

        measure '% Stock Inspecci贸n' = 
            DIVIDE([Suma Stock Inspecci贸n], [Suma Cantidad Total])

        measure '% Stock no Libre' = 
            DIVIDE([Suma Stock no Libre], [Suma Cantidad Total])

        measure '% Stock Bloqueado' = 
            DIVIDE([Suma Stock Bloqueado], [Suma Cantidad Total])


        partition Tabla_Medidas = m
            mode: import
            source =
                let
                    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
                    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"Columna1"})
                in
                    #"Columnas quitadas"

        annotation PBI_ResultType = Table
        annotation PBI_NavigationStepName = Navegaci贸n